/**
 * Admin Endpoints Configuration
 * Auto-generated from backend controllers
 * Generated At: 2025-10-15
 */

export interface AdminEndpoint {
  id: string;
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  fullPath: string;
  summary: string;
  module: string;
  handler: string;
  roles: string[];
  category?: string;
  icon?: string;
  requiredPermissions?: string[];
}

export interface AdminEndpointModule {
  name: string;
  displayName: string;
  icon: string;
  endpoints: AdminEndpoint[];
  color?: string;
}

/**
 * جميع Admin Endpoints مجمعة حسب الـ Module
 */
export const ADMIN_ENDPOINTS_BY_MODULE: Record<string, AdminEndpointModule> = {
  admin: {
    name: 'admin',
    displayName: 'الإدارة العامة',
    icon: 'dashboard',
    color: '#1976d2',
    endpoints: [
      {
        id: 'admin-dashboard',
        method: 'GET',
        path: 'dashboard',
        fullPath: '/admin/dashboard',
        summary: 'لوحة التحكم - الإحصائيات العامة',
        module: 'admin',
        handler: 'getDashboard',
        roles: ['admin', 'superadmin'],
        category: 'Dashboard',
        icon: 'dashboard',
      },
      {
        id: 'admin-today-stats',
        method: 'GET',
        path: 'stats/today',
        fullPath: '/admin/stats/today',
        summary: 'إحصائيات اليوم',
        module: 'admin',
        handler: 'getTodayStats',
        roles: ['admin', 'superadmin'],
        category: 'Statistics',
        icon: 'today',
      },
      {
        id: 'admin-system-metrics',
        method: 'GET',
        path: 'stats/system-metrics',
        fullPath: '/admin/stats/system-metrics',
        summary: 'مقاييس النظام',
        module: 'admin',
        handler: 'getSystemMetrics',
        roles: ['admin', 'superadmin'],
        category: 'Statistics',
        icon: 'analytics',
      },
      {
        id: 'admin-revenue-analytics',
        method: 'GET',
        path: 'reports/revenue',
        fullPath: '/admin/reports/revenue',
        summary: 'تحليلات الإيرادات',
        module: 'admin',
        handler: 'getRevenueAnalytics',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'attach_money',
      },
      // ... المزيد من الـ endpoints
    ],
  },
  
  drivers: {
    name: 'drivers',
    displayName: 'إدارة السائقين',
    icon: 'local_shipping',
    color: '#2e7d32',
    endpoints: [
      {
        id: 'admin-drivers-all',
        method: 'GET',
        path: 'drivers',
        fullPath: '/admin/drivers',
        summary: 'جلب كل السائقين',
        module: 'admin',
        handler: 'getAllDrivers',
        roles: ['admin', 'superadmin'],
        category: 'Drivers',
        icon: 'groups',
      },
      {
        id: 'admin-driver-details',
        method: 'GET',
        path: 'drivers/:id',
        fullPath: '/admin/drivers/:id',
        summary: 'تفاصيل سائق محدد',
        module: 'admin',
        handler: 'getDriverDetails',
        roles: ['admin', 'superadmin'],
        category: 'Drivers',
        icon: 'person',
      },
    ],
  },

  withdrawals: {
    name: 'withdrawals',
    displayName: 'طلبات السحب',
    icon: 'account_balance_wallet',
    color: '#f57c00',
    endpoints: [
      {
        id: 'admin-withdrawals-all',
        method: 'GET',
        path: 'withdrawals',
        fullPath: '/admin/withdrawals',
        summary: 'جلب طلبات السحب',
        module: 'admin',
        handler: 'getWithdrawals',
        roles: ['admin', 'superadmin'],
        category: 'Financial',
        icon: 'list',
      },
      {
        id: 'admin-withdrawals-pending',
        method: 'GET',
        path: 'withdrawals/pending',
        fullPath: '/admin/withdrawals/pending',
        summary: 'طلبات السحب المعلقة',
        module: 'admin',
        handler: 'getPendingWithdrawals',
        roles: ['admin', 'superadmin'],
        category: 'Financial',
        icon: 'pending',
      },
      {
        id: 'admin-withdrawals-approve',
        method: 'PATCH',
        path: 'withdrawals/:id/approve',
        fullPath: '/admin/withdrawals/:id/approve',
        summary: 'الموافقة على طلب سحب',
        module: 'admin',
        handler: 'approveWithdrawal',
        roles: ['admin', 'superadmin'],
        category: 'Financial',
        icon: 'check_circle',
      },
    ],
  },

  stores: {
    name: 'stores',
    displayName: 'إدارة المتاجر',
    icon: 'store',
    color: '#d32f2f',
    endpoints: [
      {
        id: 'admin-stores-pending',
        method: 'GET',
        path: 'stores/pending',
        fullPath: '/admin/stores/pending',
        summary: 'المتاجر المعلقة',
        module: 'admin',
        handler: 'getPendingStores',
        roles: ['admin', 'superadmin'],
        category: 'Moderation',
        icon: 'pending_actions',
      },
      {
        id: 'admin-stores-approve',
        method: 'POST',
        path: 'stores/:id/approve',
        fullPath: '/admin/stores/:id/approve',
        summary: 'الموافقة على متجر',
        module: 'admin',
        handler: 'approveStore',
        roles: ['admin', 'superadmin'],
        category: 'Moderation',
        icon: 'check',
      },
    ],
  },

  marketers: {
    name: 'marketers',
    displayName: 'إدارة المسوقين',
    icon: 'campaign',
    color: '#7b1fa2',
    endpoints: [
      {
        id: 'admin-marketers-all',
        method: 'GET',
        path: 'marketers',
        fullPath: '/admin/marketers',
        summary: 'جلب المسوقين الميدانيين',
        module: 'admin',
        handler: 'getAllMarketers',
        roles: ['admin', 'superadmin'],
        category: 'Marketers',
        icon: 'groups',
      },
      {
        id: 'admin-marketer-details',
        method: 'GET',
        path: 'marketers/:id',
        fullPath: '/admin/marketers/:id',
        summary: 'تفاصيل مسوق',
        module: 'admin',
        handler: 'getMarketerDetails',
        roles: ['admin', 'superadmin'],
        category: 'Marketers',
        icon: 'person',
      },
    ],
  },

  analytics: {
    name: 'analytics',
    displayName: 'التحليلات والتقارير',
    icon: 'analytics',
    color: '#0288d1',
    endpoints: [
      // ==================== ROAS ====================
      {
        id: 'analytics-roas-daily',
        method: 'GET',
        path: 'roas/daily',
        fullPath: '/analytics/roas/daily',
        summary: 'ROAS اليومي',
        module: 'analytics',
        handler: 'getDailyRoas',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'trending_up',
      },
      {
        id: 'analytics-roas-summary',
        method: 'GET',
        path: 'roas/summary',
        fullPath: '/analytics/roas/summary',
        summary: 'ملخص ROAS',
        module: 'analytics',
        handler: 'getRoasSummary',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'summarize',
      },
      {
        id: 'analytics-roas-by-platform',
        method: 'GET',
        path: 'roas/by-platform',
        fullPath: '/analytics/roas/by-platform',
        summary: 'ROAS حسب المنصة',
        module: 'analytics',
        handler: 'getRoasByPlatform',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'platform',
      },
      {
        id: 'analytics-roas-calculate',
        method: 'POST',
        path: 'roas/calculate',
        fullPath: '/analytics/roas/calculate',
        summary: 'حساب ROAS',
        module: 'analytics',
        handler: 'calculateRoas',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'calculate',
      },

      // ==================== Ad Spend ====================
      {
        id: 'analytics-adspend-record',
        method: 'POST',
        path: 'adspend',
        fullPath: '/analytics/adspend',
        summary: 'تسجيل إنفاق إعلاني',
        module: 'analytics',
        handler: 'recordAdSpend',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'attach_money',
      },
      {
        id: 'analytics-adspend-get',
        method: 'GET',
        path: 'adspend',
        fullPath: '/analytics/adspend',
        summary: 'الإنفاق الإعلاني',
        module: 'analytics',
        handler: 'getAdSpend',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'payments',
      },
      {
        id: 'analytics-adspend-summary',
        method: 'GET',
        path: 'adspend/summary',
        fullPath: '/analytics/adspend/summary',
        summary: 'ملخص الإنفاق الإعلاني',
        module: 'analytics',
        handler: 'getAdSpendSummary',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'account_balance',
      },

      // ==================== KPIs ====================
      {
        id: 'analytics-kpis',
        method: 'GET',
        path: 'kpis',
        fullPath: '/analytics/kpis',
        summary: 'مؤشرات الأداء الرئيسية',
        module: 'analytics',
        handler: 'getKPIs',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'assessment',
      },
      {
        id: 'analytics-kpis-realtime',
        method: 'GET',
        path: 'kpis/real-time',
        fullPath: '/analytics/kpis/real-time',
        summary: 'مؤشرات الأداء الحية',
        module: 'analytics',
        handler: 'getRealTimeKPIs',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'speed',
      },
      {
        id: 'analytics-kpis-trends',
        method: 'GET',
        path: 'kpis/trends',
        fullPath: '/analytics/kpis/trends',
        summary: 'اتجاهات الأداء',
        module: 'analytics',
        handler: 'getKPITrends',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'show_chart',
      },

      // ==================== Marketing Events ====================
      {
        id: 'analytics-events-track',
        method: 'POST',
        path: 'events/track',
        fullPath: '/analytics/events/track',
        summary: 'تتبع حدث تسويقي',
        module: 'analytics',
        handler: 'trackEvent',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'event',
      },
      {
        id: 'analytics-events-get',
        method: 'GET',
        path: 'events',
        fullPath: '/analytics/events',
        summary: 'الأحداث التسويقية',
        module: 'analytics',
        handler: 'getEvents',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'event_note',
      },
      {
        id: 'analytics-events-summary',
        method: 'GET',
        path: 'events/summary',
        fullPath: '/analytics/events/summary',
        summary: 'ملخص الأحداث',
        module: 'analytics',
        handler: 'getEventsSummary',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'event_available',
      },

      // ==================== Conversion Funnel ====================
      {
        id: 'analytics-funnel-conversion',
        method: 'GET',
        path: 'funnel/conversion',
        fullPath: '/analytics/funnel/conversion',
        summary: 'قمع التحويل',
        module: 'analytics',
        handler: 'getConversionFunnel',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'filter_list',
      },
      {
        id: 'analytics-funnel-dropoff',
        method: 'GET',
        path: 'funnel/drop-off',
        fullPath: '/analytics/funnel/drop-off',
        summary: 'نقاط الانسحاب',
        module: 'analytics',
        handler: 'getDropOffPoints',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'arrow_drop_down',
      },

      // ==================== User Analytics ====================
      {
        id: 'analytics-users-growth',
        method: 'GET',
        path: 'users/growth',
        fullPath: '/analytics/users/growth',
        summary: 'نمو المستخدمين',
        module: 'analytics',
        handler: 'getUserGrowth',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'trending_up',
      },
      {
        id: 'analytics-users-retention',
        method: 'GET',
        path: 'users/retention',
        fullPath: '/analytics/users/retention',
        summary: 'معدل الاحتفاظ',
        module: 'analytics',
        handler: 'getUserRetention',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'group',
      },
      {
        id: 'analytics-users-cohort',
        method: 'GET',
        path: 'users/cohort',
        fullPath: '/analytics/users/cohort',
        summary: 'تحليل الأفواج',
        module: 'analytics',
        handler: 'getCohortAnalysis',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'groups',
      },

      // ==================== Revenue Analytics ====================
      {
        id: 'analytics-revenue-forecast',
        method: 'GET',
        path: 'revenue/forecast',
        fullPath: '/analytics/revenue/forecast',
        summary: 'توقعات الإيرادات',
        module: 'analytics',
        handler: 'getRevenueForecast',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'timeline',
      },
      {
        id: 'analytics-revenue-breakdown',
        method: 'GET',
        path: 'revenue/breakdown',
        fullPath: '/analytics/revenue/breakdown',
        summary: 'تفصيل الإيرادات',
        module: 'analytics',
        handler: 'getRevenueBreakdown',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'pie_chart',
      },

      // ==================== Advanced Analytics ====================
      {
        id: 'analytics-advanced-dashboard-overview',
        method: 'GET',
        path: 'advanced/dashboard-overview',
        fullPath: '/analytics/advanced/dashboard-overview',
        summary: 'نظرة عامة متقدمة',
        module: 'analytics',
        handler: 'getDashboardOverview',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'dashboard',
      },
      {
        id: 'analytics-advanced-cohort',
        method: 'GET',
        path: 'advanced/cohort-analysis-advanced',
        fullPath: '/analytics/advanced/cohort-analysis-advanced',
        summary: 'تحليل المجموعات المتقدم',
        module: 'analytics',
        handler: 'getCohortAnalysisAdvanced',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'analytics',
      },
      {
        id: 'analytics-advanced-funnel',
        method: 'GET',
        path: 'advanced/funnel-analysis',
        fullPath: '/analytics/advanced/funnel-analysis',
        summary: 'تحليل القمع',
        module: 'analytics',
        handler: 'getFunnelAnalysis',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'filter_alt',
      },
      {
        id: 'analytics-advanced-retention',
        method: 'GET',
        path: 'advanced/retention',
        fullPath: '/analytics/advanced/retention',
        summary: 'معدل الاحتفاظ',
        module: 'analytics',
        handler: 'getRetentionRate',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'repeat',
      },
      {
        id: 'analytics-advanced-ltv',
        method: 'GET',
        path: 'advanced/ltv',
        fullPath: '/analytics/advanced/ltv',
        summary: 'القيمة الدائمة للعميل',
        module: 'analytics',
        handler: 'getCustomerLTV',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'star',
      },
      {
        id: 'analytics-advanced-churn',
        method: 'GET',
        path: 'advanced/churn-rate',
        fullPath: '/analytics/advanced/churn-rate',
        summary: 'معدل التراجع',
        module: 'analytics',
        handler: 'getChurnRate',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'arrow_downward',
      },
      {
        id: 'analytics-advanced-geo',
        method: 'GET',
        path: 'advanced/geographic-distribution',
        fullPath: '/analytics/advanced/geographic-distribution',
        summary: 'التوزيع الجغرافي',
        module: 'analytics',
        handler: 'getGeographicDistribution',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'map',
      },
      {
        id: 'analytics-advanced-peak-hours',
        method: 'GET',
        path: 'advanced/peak-hours',
        fullPath: '/analytics/advanced/peak-hours',
        summary: 'ساعات الذروة',
        module: 'analytics',
        handler: 'getPeakHours',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'schedule',
      },
      {
        id: 'analytics-advanced-product-performance',
        method: 'GET',
        path: 'advanced/product-performance',
        fullPath: '/analytics/advanced/product-performance',
        summary: 'أداء المنتجات',
        module: 'analytics',
        handler: 'getProductPerformance',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'inventory',
      },
      {
        id: 'analytics-advanced-driver-performance',
        method: 'GET',
        path: 'advanced/driver-performance',
        fullPath: '/analytics/advanced/driver-performance',
        summary: 'أداء السائقين',
        module: 'analytics',
        handler: 'getDriverPerformance',
        roles: ['admin', 'superadmin'],
        category: 'Analytics',
        icon: 'local_shipping',
      },
    ],
  },

  finance: {
    name: 'finance',
    displayName: 'الإدارة المالية',
    icon: 'account_balance',
    color: '#388e3c',
    endpoints: [
      // ==================== Commissions ====================
      {
        id: 'finance-commission-create',
        method: 'POST',
        path: 'commissions',
        fullPath: '/finance/commissions',
        summary: 'إنشاء عمولة جديدة',
        module: 'finance',
        handler: 'createCommission',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'add_circle',
      },
      {
        id: 'finance-commission-approve',
        method: 'PATCH',
        path: 'commissions/:id/approve',
        fullPath: '/finance/commissions/:id/approve',
        summary: 'الموافقة على عمولة',
        module: 'finance',
        handler: 'approveCommission',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'check_circle',
      },
      {
        id: 'finance-commission-cancel',
        method: 'PATCH',
        path: 'commissions/:id/cancel',
        fullPath: '/finance/commissions/:id/cancel',
        summary: 'إلغاء عمولة',
        module: 'finance',
        handler: 'cancelCommission',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'cancel',
      },

      // ==================== Payout Batches ====================
      {
        id: 'finance-payout-batch-create',
        method: 'POST',
        path: 'payouts/batches',
        fullPath: '/finance/payouts/batches',
        summary: 'إنشاء دفعة من العمولات',
        module: 'finance',
        handler: 'createPayoutBatch',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'account_balance_wallet',
      },
      {
        id: 'finance-payout-batches-all',
        method: 'GET',
        path: 'payouts/batches',
        fullPath: '/finance/payouts/batches',
        summary: 'الحصول على كل الدفعات',
        module: 'finance',
        handler: 'getPayoutBatches',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'list',
      },
      {
        id: 'finance-payout-batch-get',
        method: 'GET',
        path: 'payouts/batches/:id',
        fullPath: '/finance/payouts/batches/:id',
        summary: 'الحصول على دفعة',
        module: 'finance',
        handler: 'getPayoutBatch',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'receipt',
      },
      {
        id: 'finance-payout-batch-items',
        method: 'GET',
        path: 'payouts/batches/:id/items',
        fullPath: '/finance/payouts/batches/:id/items',
        summary: 'الحصول على عناصر دفعة',
        module: 'finance',
        handler: 'getPayoutBatchItems',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'list_alt',
      },
      {
        id: 'finance-payout-batch-approve',
        method: 'PATCH',
        path: 'payouts/batches/:id/approve',
        fullPath: '/finance/payouts/batches/:id/approve',
        summary: 'الموافقة على دفعة',
        module: 'finance',
        handler: 'approvePayoutBatch',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'verified',
      },
      {
        id: 'finance-payout-batch-complete',
        method: 'PATCH',
        path: 'payouts/batches/:id/complete',
        fullPath: '/finance/payouts/batches/:id/complete',
        summary: 'إكمال دفعة',
        module: 'finance',
        handler: 'completePayoutBatch',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'done_all',
      },

      // ==================== Settlements ====================
      {
        id: 'finance-settlement-create',
        method: 'POST',
        path: 'settlements',
        fullPath: '/finance/settlements',
        summary: 'إنشاء تسوية',
        module: 'finance',
        handler: 'createSettlement',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'receipt_long',
      },
      {
        id: 'finance-settlement-entity',
        method: 'GET',
        path: 'settlements/entity/:entityId',
        fullPath: '/finance/settlements/entity/:entityId',
        summary: 'الحصول على تسويات كيان',
        module: 'finance',
        handler: 'getEntitySettlements',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'list',
      },
      {
        id: 'finance-settlement-get',
        method: 'GET',
        path: 'settlements/:id',
        fullPath: '/finance/settlements/:id',
        summary: 'الحصول على تسوية',
        module: 'finance',
        handler: 'getSettlement',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'description',
      },
      {
        id: 'finance-settlement-approve',
        method: 'PATCH',
        path: 'settlements/:id/approve',
        fullPath: '/finance/settlements/:id/approve',
        summary: 'الموافقة على تسوية',
        module: 'finance',
        handler: 'approveSettlement',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'check',
      },

      // ==================== Coupons ====================
      {
        id: 'finance-coupon-create',
        method: 'POST',
        path: 'coupons',
        fullPath: '/finance/coupons',
        summary: 'إنشاء كوبون',
        module: 'finance',
        handler: 'createCoupon',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'confirmation_number',
      },
      {
        id: 'finance-coupons-all',
        method: 'GET',
        path: 'coupons',
        fullPath: '/finance/coupons',
        summary: 'الحصول على كل الكوبونات',
        module: 'finance',
        handler: 'getCoupons',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'local_offer',
      },
      {
        id: 'finance-coupon-update',
        method: 'PATCH',
        path: 'coupons/:id',
        fullPath: '/finance/coupons/:id',
        summary: 'تحديث كوبون',
        module: 'finance',
        handler: 'updateCoupon',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'edit',
      },

      // ==================== Reconciliations ====================
      {
        id: 'finance-reconciliation-create',
        method: 'POST',
        path: 'reconciliations',
        fullPath: '/finance/reconciliations',
        summary: 'إنشاء مطابقة مالية',
        module: 'finance',
        handler: 'createReconciliation',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'compare_arrows',
      },
      {
        id: 'finance-reconciliations-all',
        method: 'GET',
        path: 'reconciliations',
        fullPath: '/finance/reconciliations',
        summary: 'الحصول على كل المطابقات',
        module: 'finance',
        handler: 'getReconciliations',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'list',
      },
      {
        id: 'finance-reconciliation-get',
        method: 'GET',
        path: 'reconciliations/:id',
        fullPath: '/finance/reconciliations/:id',
        summary: 'الحصول على مطابقة',
        module: 'finance',
        handler: 'getReconciliation',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'description',
      },
      {
        id: 'finance-reconciliation-add-actuals',
        method: 'PATCH',
        path: 'reconciliations/:id/actual-totals',
        fullPath: '/finance/reconciliations/:id/actual-totals',
        summary: 'إضافة الإجماليات الفعلية',
        module: 'finance',
        handler: 'addActualTotals',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'add',
      },
      {
        id: 'finance-reconciliation-add-issue',
        method: 'POST',
        path: 'reconciliations/:id/issues',
        fullPath: '/finance/reconciliations/:id/issues',
        summary: 'إضافة مشكلة للمطابقة',
        module: 'finance',
        handler: 'addReconciliationIssue',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'warning',
      },
      {
        id: 'finance-reconciliation-resolve-issue',
        method: 'PATCH',
        path: 'reconciliations/:id/issues/:issueIndex/resolve',
        fullPath: '/finance/reconciliations/:id/issues/:issueIndex/resolve',
        summary: 'حل مشكلة في المطابقة',
        module: 'finance',
        handler: 'resolveReconciliationIssue',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'check_circle',
      },

      // ==================== Reports ====================
      {
        id: 'finance-report-daily-generate',
        method: 'POST',
        path: 'reports/daily',
        fullPath: '/finance/reports/daily',
        summary: 'إنشاء تقرير يومي',
        module: 'finance',
        handler: 'generateDailyReport',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'summarize',
      },
      {
        id: 'finance-report-daily-get',
        method: 'GET',
        path: 'reports/daily/:date',
        fullPath: '/finance/reports/daily/:date',
        summary: 'الحصول على تقرير يومي',
        module: 'finance',
        handler: 'getDailyReport',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'today',
      },
      {
        id: 'finance-reports-get',
        method: 'GET',
        path: 'reports',
        fullPath: '/finance/reports',
        summary: 'الحصول على التقارير',
        module: 'finance',
        handler: 'getReports',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'assessment',
      },
      {
        id: 'finance-report-finalize',
        method: 'PATCH',
        path: 'reports/:id/finalize',
        fullPath: '/finance/reports/:id/finalize',
        summary: 'تثبيت تقرير',
        module: 'finance',
        handler: 'finalizeReport',
        roles: ['admin', 'superadmin'],
        category: 'Finance',
        icon: 'lock',
      },
    ],
  },

  akhdimni: {
    name: 'akhdimni',
    displayName: 'خدمة أخدمني',
    icon: 'delivery_dining',
    color: '#ff6f00',
    endpoints: [
      {
        id: 'akhdimni-admin-errands',
        method: 'GET',
        path: 'admin/errands',
        fullPath: '/akhdimni/admin/errands',
        summary: 'كل طلبات أخدمني (إدارة)',
        module: 'akhdimni',
        handler: 'getAllErrands',
        roles: ['admin', 'superadmin'],
        category: 'Errands',
        icon: 'list_alt',
      },
      {
        id: 'akhdimni-assign-driver',
        method: 'POST',
        path: 'admin/errands/:id/assign-driver',
        fullPath: '/akhdimni/admin/errands/:id/assign-driver',
        summary: 'تعيين سائق لمهمة',
        module: 'akhdimni',
        handler: 'assignDriver',
        roles: ['admin', 'superadmin'],
        category: 'Errands',
        icon: 'person_add',
      },
    ],
  },

  amani: {
    name: 'amani',
    displayName: 'الأماني',
    icon: 'star',
    color: '#9c27b0',
    endpoints: [
      {
        id: 'amani-admin-list',
        method: 'GET',
        path: 'amani',
        fullPath: '/admin/amani',
        summary: 'قائمة طلبات الأماني',
        module: 'amani',
        handler: 'list',
        roles: ['admin', 'superadmin'],
        category: 'Amani',
        icon: 'list',
      },
      {
        id: 'amani-admin-status-update',
        method: 'PATCH',
        path: 'amani/:id/status',
        fullPath: '/admin/amani/:id/status',
        summary: 'تحديث حالة طلب أماني',
        module: 'amani',
        handler: 'setStatus',
        roles: ['admin', 'superadmin'],
        category: 'Amani',
        icon: 'edit',
      },
      {
        id: 'amani-admin-delete',
        method: 'DELETE',
        path: 'amani/:id',
        fullPath: '/admin/amani/:id',
        summary: 'حذف طلب أماني',
        module: 'amani',
        handler: 'remove',
        roles: ['admin', 'superadmin'],
        category: 'Amani',
        icon: 'delete',
      },
    ],
  },

  arabon: {
    name: 'arabon',
    displayName: 'العربون',
    icon: 'payments',
    color: '#ff9800',
    endpoints: [
      {
        id: 'arabon-admin-list',
        method: 'GET',
        path: 'arabon',
        fullPath: '/admin/arabon',
        summary: 'قائمة طلبات العربون',
        module: 'arabon',
        handler: 'list',
        roles: ['admin', 'superadmin'],
        category: 'Arabon',
        icon: 'list',
      },
      {
        id: 'arabon-admin-status-update',
        method: 'PATCH',
        path: 'arabon/:id/status',
        fullPath: '/admin/arabon/:id/status',
        summary: 'تحديث حالة طلب عربون',
        module: 'arabon',
        handler: 'setStatus',
        roles: ['admin', 'superadmin'],
        category: 'Arabon',
        icon: 'edit',
      },
      {
        id: 'arabon-admin-get-one',
        method: 'GET',
        path: 'arabon/:id',
        fullPath: '/admin/arabon/:id',
        summary: 'جلب تفاصيل طلب عربون',
        module: 'arabon',
        handler: 'getOne',
        roles: ['admin', 'superadmin'],
        category: 'Arabon',
        icon: 'view',
      },
      {
        id: 'arabon-admin-delete',
        method: 'DELETE',
        path: 'arabon/:id',
        fullPath: '/admin/arabon/:id',
        summary: 'حذف طلب عربون',
        module: 'arabon',
        handler: 'remove',
        roles: ['admin', 'superadmin'],
        category: 'Arabon',
        icon: 'delete',
      },
    ],
  },

  es3afni: {
    name: 'es3afni',
    displayName: 'إسعفني',
    icon: 'bloodtype',
    color: '#d32f2f',
    endpoints: [
      {
        id: 'es3afni-admin-list',
        method: 'GET',
        path: 'es3afni',
        fullPath: '/admin/es3afni',
        summary: 'قائمة بلاغات إسعفني',
        module: 'es3afni',
        handler: 'list',
        roles: ['admin', 'superadmin'],
        category: 'Es3afni',
        icon: 'list',
      },
      {
        id: 'es3afni-admin-status-update',
        method: 'PATCH',
        path: 'es3afni/:id/status',
        fullPath: '/admin/es3afni/:id/status',
        summary: 'تحديث حالة بلاغ إسعفني',
        module: 'es3afni',
        handler: 'setStatus',
        roles: ['admin', 'superadmin'],
        category: 'Es3afni',
        icon: 'edit',
      },
      {
        id: 'es3afni-admin-delete',
        method: 'DELETE',
        path: 'es3afni/:id',
        fullPath: '/admin/es3afni/:id',
        summary: 'حذف بلاغ إسعفني',
        module: 'es3afni',
        handler: 'remove',
        roles: ['admin', 'superadmin'],
        category: 'Es3afni',
        icon: 'delete',
      },
    ],
  },

  er: {
    name: 'er',
    displayName: 'الموارد البشرية والمحاسبة',
    icon: 'business',
    color: '#4a148c',
    endpoints: [
      // ==================== Employees ====================
      {
        id: 'er-employees-create',
        method: 'POST',
        path: 'employees',
        fullPath: '/er/employees',
        summary: 'إضافة موظف جديد',
        module: 'er',
        handler: 'createEmployee',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'person_add',
      },
      {
        id: 'er-employees-all',
        method: 'GET',
        path: 'employees',
        fullPath: '/er/employees',
        summary: 'الحصول على كل الموظفين',
        module: 'er',
        handler: 'getAllEmployees',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'groups',
      },
      {
        id: 'er-employee-get',
        method: 'GET',
        path: 'employees/:id',
        fullPath: '/er/employees/:id',
        summary: 'الحصول على موظف محدد',
        module: 'er',
        handler: 'getEmployee',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'person',
      },
      {
        id: 'er-employee-update',
        method: 'PATCH',
        path: 'employees/:id',
        fullPath: '/er/employees/:id',
        summary: 'تحديث موظف',
        module: 'er',
        handler: 'updateEmployee',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'edit',
      },

      // ==================== Attendance ====================
      {
        id: 'er-attendance-get',
        method: 'GET',
        path: 'attendance/:employeeId',
        fullPath: '/er/attendance/:employeeId',
        summary: 'سجل حضور موظف',
        module: 'er',
        handler: 'getEmployeeAttendance',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'event_available',
      },

      // ==================== Leave Requests ====================
      {
        id: 'er-leave-approve',
        method: 'PATCH',
        path: 'leave-requests/:id/approve',
        fullPath: '/er/leave-requests/:id/approve',
        summary: 'الموافقة على طلب إجازة',
        module: 'er',
        handler: 'approveLeaveRequest',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'check_circle',
      },
      {
        id: 'er-leave-reject',
        method: 'PATCH',
        path: 'leave-requests/:id/reject',
        fullPath: '/er/leave-requests/:id/reject',
        summary: 'رفض طلب إجازة',
        module: 'er',
        handler: 'rejectLeaveRequest',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'cancel',
      },

      // ==================== Payroll ====================
      {
        id: 'er-payroll-generate',
        method: 'POST',
        path: 'payroll/generate',
        fullPath: '/er/payroll/generate',
        summary: 'إنشاء كشف راتب',
        module: 'er',
        handler: 'generatePayroll',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'payments',
      },
      {
        id: 'er-payroll-approve',
        method: 'PATCH',
        path: 'payroll/:id/approve',
        fullPath: '/er/payroll/:id/approve',
        summary: 'الموافقة على كشف راتب',
        module: 'er',
        handler: 'approvePayroll',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'check',
      },
      {
        id: 'er-payroll-mark-paid',
        method: 'PATCH',
        path: 'payroll/:id/mark-paid',
        fullPath: '/er/payroll/:id/mark-paid',
        summary: 'تحديد كمدفوع',
        module: 'er',
        handler: 'markAsPaid',
        roles: ['admin', 'superadmin'],
        category: 'HR',
        icon: 'done_all',
      },

      // ==================== Accounting ====================
      {
        id: 'er-accounts-create',
        method: 'POST',
        path: 'accounts',
        fullPath: '/er/accounts',
        summary: 'إنشاء حساب',
        module: 'er',
        handler: 'createAccount',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'account_balance',
      },
      {
        id: 'er-accounts-all',
        method: 'GET',
        path: 'accounts',
        fullPath: '/er/accounts',
        summary: 'دليل الحسابات',
        module: 'er',
        handler: 'getAccounts',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'list',
      },
      {
        id: 'er-account-get',
        method: 'GET',
        path: 'accounts/:id',
        fullPath: '/er/accounts/:id',
        summary: 'الحصول على حساب',
        module: 'er',
        handler: 'getAccount',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'account_circle',
      },
      {
        id: 'er-journal-create',
        method: 'POST',
        path: 'journal-entries',
        fullPath: '/er/journal-entries',
        summary: 'إنشاء قيد يومية',
        module: 'er',
        handler: 'createJournalEntry',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'receipt_long',
      },
      {
        id: 'er-journal-all',
        method: 'GET',
        path: 'journal-entries',
        fullPath: '/er/journal-entries',
        summary: 'الحصول على قيود اليومية',
        module: 'er',
        handler: 'getJournalEntries',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'list_alt',
      },
      {
        id: 'er-journal-post',
        method: 'PATCH',
        path: 'journal-entries/:id/post',
        fullPath: '/er/journal-entries/:id/post',
        summary: 'ترحيل قيد',
        module: 'er',
        handler: 'postJournalEntry',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'send',
      },
      {
        id: 'er-trial-balance',
        method: 'GET',
        path: 'reports/trial-balance',
        fullPath: '/er/reports/trial-balance',
        summary: 'ميزان المراجعة',
        module: 'er',
        handler: 'getTrialBalance',
        roles: ['admin', 'superadmin'],
        category: 'Accounting',
        icon: 'balance',
      },
    ],
  },

  health: {
    name: 'health',
    displayName: 'الفحص الصحي',
    icon: 'monitor_heart',
    color: '#c62828',
    endpoints: [
      {
        id: 'health-check',
        method: 'GET',
        path: '',
        fullPath: '/health',
        summary: 'الفحص الصحي الشامل',
        module: 'health',
        handler: 'check',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'health_and_safety',
      },
      {
        id: 'health-liveness',
        method: 'GET',
        path: 'liveness',
        fullPath: '/health/liveness',
        summary: 'Liveness Probe',
        module: 'health',
        handler: 'liveness',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'favorite',
      },
      {
        id: 'health-readiness',
        method: 'GET',
        path: 'readiness',
        fullPath: '/health/readiness',
        summary: 'Readiness Probe',
        module: 'health',
        handler: 'readiness',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'check_circle',
      },
      {
        id: 'health-advanced',
        method: 'GET',
        path: 'advanced',
        fullPath: '/health/advanced',
        summary: 'فحص متقدم شامل',
        module: 'health',
        handler: 'advanced',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'analytics',
      },
      {
        id: 'health-detailed',
        method: 'GET',
        path: 'detailed',
        fullPath: '/health/detailed',
        summary: 'فحص تفصيلي',
        module: 'health',
        handler: 'detailed',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'info',
      },
      {
        id: 'health-metrics',
        method: 'GET',
        path: 'metrics',
        fullPath: '/health/metrics',
        summary: 'مقاييس الصحة',
        module: 'health',
        handler: 'metrics',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'speed',
      },
      {
        id: 'health-info',
        method: 'GET',
        path: 'info',
        fullPath: '/health/info',
        summary: 'معلومات التطبيق',
        module: 'health',
        handler: 'info',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'info',
      },
    ],
  },

  support: {
    name: 'support',
    displayName: 'الدعم الفني',
    icon: 'support_agent',
    color: '#00796b',
    endpoints: [
      {
        id: 'support-tickets-all',
        method: 'GET',
        path: 'tickets',
        fullPath: '/support/tickets',
        summary: 'جلب التذاكر',
        module: 'support',
        handler: 'getTickets',
        roles: ['admin', 'superadmin'],
        category: 'Support',
        icon: 'confirmation_number',
      },
      {
        id: 'support-ticket-get',
        method: 'GET',
        path: 'tickets/:id',
        fullPath: '/support/tickets/:id',
        summary: 'تفاصيل تذكرة',
        module: 'support',
        handler: 'getTicketById',
        roles: ['admin', 'superadmin'],
        category: 'Support',
        icon: 'description',
      },
      {
        id: 'support-ticket-add-message',
        method: 'PATCH',
        path: 'tickets/:id/messages',
        fullPath: '/support/tickets/:id/messages',
        summary: 'إضافة رسالة للتذكرة',
        module: 'support',
        handler: 'addMessage',
        roles: ['admin', 'superadmin'],
        category: 'Support',
        icon: 'message',
      },
      {
        id: 'support-stats',
        method: 'GET',
        path: 'stats',
        fullPath: '/support/stats',
        summary: 'إحصائيات التذاكر',
        module: 'support',
        handler: 'getStats',
        roles: ['admin', 'superadmin'],
        category: 'Support',
        icon: 'analytics',
      },
    ],
  },

  metrics: {
    name: 'metrics',
    displayName: 'المقاييس والإحصائيات',
    icon: 'insights',
    color: '#1565c0',
    endpoints: [
      {
        id: 'metrics-prometheus',
        method: 'GET',
        path: '',
        fullPath: '/metrics',
        summary: 'Prometheus Metrics',
        module: 'metrics',
        handler: 'getPrometheusMetrics',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'bar_chart',
      },
      {
        id: 'metrics-json',
        method: 'GET',
        path: 'json',
        fullPath: '/metrics/json',
        summary: 'Metrics in JSON format',
        module: 'metrics',
        handler: 'getJsonMetrics',
        roles: ['admin', 'superadmin'],
        category: 'System',
        icon: 'data_object',
      },
    ],
  },

  legal: {
    name: 'legal',
    displayName: 'النظام القانوني',
    icon: 'gavel',
    color: '#5d4037',
    endpoints: [
      {
        id: 'legal-privacy-policies-all',
        method: 'GET',
        path: 'admin/privacy-policies',
        fullPath: '/legal/admin/privacy-policies',
        summary: 'جميع سياسات الخصوصية',
        module: 'legal',
        handler: 'getAllPrivacyPolicies',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'policy',
      },
      {
        id: 'legal-privacy-policy-create',
        method: 'POST',
        path: 'admin/privacy-policy',
        fullPath: '/legal/admin/privacy-policy',
        summary: 'إنشاء سياسة خصوصية',
        module: 'legal',
        handler: 'createPrivacyPolicy',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'add',
      },
      {
        id: 'legal-privacy-policy-activate',
        method: 'PATCH',
        path: 'admin/privacy-policy/:id/activate',
        fullPath: '/legal/admin/privacy-policy/:id/activate',
        summary: 'تفعيل سياسة خصوصية',
        module: 'legal',
        handler: 'activatePrivacyPolicy',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'toggle_on',
      },
      {
        id: 'legal-terms-all',
        method: 'GET',
        path: 'admin/terms-of-service',
        fullPath: '/legal/admin/terms-of-service',
        summary: 'جميع شروط الخدمة',
        module: 'legal',
        handler: 'getAllTermsOfService',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'description',
      },
      {
        id: 'legal-terms-create',
        method: 'POST',
        path: 'admin/terms-of-service',
        fullPath: '/legal/admin/terms-of-service',
        summary: 'إنشاء شروط خدمة',
        module: 'legal',
        handler: 'createTermsOfService',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'add',
      },
      {
        id: 'legal-terms-activate',
        method: 'PATCH',
        path: 'admin/terms-of-service/:id/activate',
        fullPath: '/legal/admin/terms-of-service/:id/activate',
        summary: 'تفعيل شروط خدمة',
        module: 'legal',
        handler: 'activateTermsOfService',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'toggle_on',
      },
      {
        id: 'legal-consent-statistics',
        method: 'GET',
        path: 'admin/consent/statistics',
        fullPath: '/legal/admin/consent/statistics',
        summary: 'إحصائيات الموافقات',
        module: 'legal',
        handler: 'getConsentStatistics',
        roles: ['admin', 'superadmin'],
        category: 'Legal',
        icon: 'analytics',
      },
    ],
  },

  content: {
    name: 'content',
    displayName: 'إدارة المحتوى',
    icon: 'article',
    color: '#6a1b9a',
    endpoints: [
      // ==================== Banners ====================
      {
        id: 'content-admin-banners-all',
        method: 'GET',
        path: 'admin/banners',
        fullPath: '/content/admin/banners',
        summary: 'كل البانرات',
        module: 'content',
        handler: 'getAllBanners',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'view_carousel',
      },
      {
        id: 'content-banner-create',
        method: 'POST',
        path: 'banners',
        fullPath: '/content/banners',
        summary: 'إنشاء بانر جديد',
        module: 'content',
        handler: 'createBanner',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'add_photo_alternate',
      },
      {
        id: 'content-banner-update',
        method: 'PATCH',
        path: 'banners/:id',
        fullPath: '/content/banners/:id',
        summary: 'تحديث بانر',
        module: 'content',
        handler: 'updateBanner',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'edit',
      },
      {
        id: 'content-banner-delete',
        method: 'DELETE',
        path: 'banners/:id',
        fullPath: '/content/banners/:id',
        summary: 'حذف بانر',
        module: 'content',
        handler: 'deleteBanner',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'delete',
      },

      // ==================== CMS Pages ====================
      {
        id: 'content-admin-pages-create',
        method: 'POST',
        path: 'admin/pages',
        fullPath: '/content/admin/pages',
        summary: 'إنشاء صفحة CMS',
        module: 'content',
        handler: 'createCMSPage',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'post_add',
      },
      {
        id: 'content-admin-pages-update',
        method: 'PATCH',
        path: 'admin/pages/:id',
        fullPath: '/content/admin/pages/:id',
        summary: 'تحديث صفحة CMS',
        module: 'content',
        handler: 'updateCMSPage',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'edit_note',
      },

      // ==================== App Settings ====================
      {
        id: 'content-admin-settings-update',
        method: 'PATCH',
        path: 'admin/app-settings',
        fullPath: '/content/admin/app-settings',
        summary: 'تحديث إعدادات التطبيق',
        module: 'content',
        handler: 'updateAppSettings',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'settings',
      },

      // ==================== FAQs ====================
      {
        id: 'content-admin-faqs-create',
        method: 'POST',
        path: 'admin/faqs',
        fullPath: '/content/admin/faqs',
        summary: 'إضافة سؤال شائع',
        module: 'content',
        handler: 'createFAQ',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'help',
      },
      {
        id: 'content-admin-faqs-update',
        method: 'PATCH',
        path: 'admin/faqs/:id',
        fullPath: '/content/admin/faqs/:id',
        summary: 'تحديث سؤال شائع',
        module: 'content',
        handler: 'updateFAQ',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'edit',
      },
      {
        id: 'content-admin-faqs-delete',
        method: 'DELETE',
        path: 'admin/faqs/:id',
        fullPath: '/content/admin/faqs/:id',
        summary: 'حذف سؤال شائع',
        module: 'content',
        handler: 'deleteFAQ',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'delete',
      },

      // ==================== Subscription Plans ====================
      {
        id: 'content-subscription-plans-create',
        method: 'POST',
        path: 'subscription-plans',
        fullPath: '/content/subscription-plans',
        summary: 'إنشاء خطة اشتراك',
        module: 'content',
        handler: 'createSubscriptionPlan',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'card_membership',
      },

      // ==================== Public Endpoints (for admin view) ====================
      {
        id: 'content-banners-get',
        method: 'GET',
        path: 'banners',
        fullPath: '/content/banners',
        summary: 'جلب البانرات النشطة',
        module: 'content',
        handler: 'getActiveBanners',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'view_list',
      },
      {
        id: 'content-pages-get',
        method: 'GET',
        path: 'pages',
        fullPath: '/content/pages',
        summary: 'جلب صفحات CMS',
        module: 'content',
        handler: 'getCMSPages',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'pages',
      },
      {
        id: 'content-app-settings-get',
        method: 'GET',
        path: 'app-settings',
        fullPath: '/content/app-settings',
        summary: 'جلب إعدادات التطبيق',
        module: 'content',
        handler: 'getAppSettings',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'settings_applications',
      },
      {
        id: 'content-faqs-get',
        method: 'GET',
        path: 'faqs',
        fullPath: '/content/faqs',
        summary: 'جلب الأسئلة الشائعة',
        module: 'content',
        handler: 'getFAQs',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'quiz',
      },
      {
        id: 'content-subscription-plans-get',
        method: 'GET',
        path: 'subscription-plans',
        fullPath: '/content/subscription-plans',
        summary: 'جلب خطط الاشتراك',
        module: 'content',
        handler: 'getSubscriptionPlans',
        roles: ['admin', 'superadmin'],
        category: 'Content',
        icon: 'subscriptions',
      },
    ],
  },
};

/**
 * جميع الـ Endpoints في مصفوفة واحدة
 */
export const ALL_ADMIN_ENDPOINTS: AdminEndpoint[] = Object.values(
  ADMIN_ENDPOINTS_BY_MODULE
).flatMap((module) => module.endpoints);

/**
 * الحصول على endpoints حسب الـ category
 */
export function getEndpointsByCategory(category: string): AdminEndpoint[] {
  return ALL_ADMIN_ENDPOINTS.filter((ep) => ep.category === category);
}

/**
 * الحصول على endpoints حسب الـ module
 */
export function getEndpointsByModule(moduleName: string): AdminEndpoint[] {
  return ADMIN_ENDPOINTS_BY_MODULE[moduleName]?.endpoints || [];
}

/**
 * الحصول على endpoint بواسطة ID
 */
export function getEndpointById(id: string): AdminEndpoint | undefined {
  return ALL_ADMIN_ENDPOINTS.find((ep) => ep.id === id);
}

/**
 * Categories للتنظيم في الـ UI
 */
export const ENDPOINT_CATEGORIES = [
  { id: 'Dashboard', label: 'لوحة التحكم', icon: 'dashboard' },
  { id: 'Statistics', label: 'الإحصائيات', icon: 'bar_chart' },
  { id: 'Drivers', label: 'السائقين', icon: 'local_shipping' },
  { id: 'Financial', label: 'المالية', icon: 'account_balance' },
  { id: 'Moderation', label: 'المراجعة والموافقات', icon: 'verified' },
  { id: 'Marketers', label: 'المسوقين', icon: 'campaign' },
  { id: 'Analytics', label: 'التحليلات', icon: 'analytics' },
  { id: 'Finance', label: 'الإدارة المالية', icon: 'account_balance' },
  { id: 'Errands', label: 'أخدمني', icon: 'delivery_dining' },
];

/**
 * الحصول على كل الـ modules
 */
export const ALL_MODULES = Object.values(ADMIN_ENDPOINTS_BY_MODULE);

/**
 * إحصائيات عامة
 */
export const ENDPOINTS_STATS = {
  total: ALL_ADMIN_ENDPOINTS.length,
  byMethod: {
    GET: ALL_ADMIN_ENDPOINTS.filter((ep) => ep.method === 'GET').length,
    POST: ALL_ADMIN_ENDPOINTS.filter((ep) => ep.method === 'POST').length,
    PATCH: ALL_ADMIN_ENDPOINTS.filter((ep) => ep.method === 'PATCH').length,
    PUT: ALL_ADMIN_ENDPOINTS.filter((ep) => ep.method === 'PUT').length,
    DELETE: ALL_ADMIN_ENDPOINTS.filter((ep) => ep.method === 'DELETE').length,
  },
  modules: Object.keys(ADMIN_ENDPOINTS_BY_MODULE).length,
};

/**
 * Helper لبناء الـ URL الكامل
 */
export function buildEndpointUrl(
  endpoint: AdminEndpoint,
  params?: Record<string, string>,
  baseUrl: string = import.meta.env.VITE_API_BASE_URL || 'https://api.bthwani.com/api/v1'
): string {
  let url = `${baseUrl}${endpoint.fullPath}`;
  
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      url = url.replace(`:${key}`, value);
    });
  }
  
  return url;
}

/**
 * Type guard للتحقق من صلاحيات المستخدم
 */
export function hasPermission(
  userRoles: string[],
  endpoint: AdminEndpoint
): boolean {
  return endpoint.roles.some((role) => userRoles.includes(role));
}

/**
 * Filter endpoints حسب صلاحيات المستخدم
 */
export function filterEndpointsByPermissions(
  userRoles: string[]
): AdminEndpoint[] {
  return ALL_ADMIN_ENDPOINTS.filter((ep) => hasPermission(userRoles, ep));
}

